# Generated by Django 4.1 on 2022-09-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzivatel',
            options={'verbose_name': 'Uživatel', 'verbose_name_plural': 'Uživatelé'},
        ),
    ]
