# Generated by Django 4.1 on 2022-09-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0002_alter_uzivatel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzivatel',
            options={'verbose_name': 'uživatel', 'verbose_name_plural': 'uživatelé'},
        ),
        migrations.AddField(
            model_name='uzivatel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='uzivatel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uzivatel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='uzivatel',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='uzivatel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
