# Generated by Django 4.1 on 2022-09-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0003_alter_uzivatel_options_uzivatel_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzivatel',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='uzivatel',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
    ]
