# Generated by Django 4.1 on 2022-09-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0004_remove_uzivatel_is_active_alter_uzivatel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=50, verbose_name='Příjmení')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('telefon', models.CharField(max_length=50, verbose_name='Telefon')),
                ('ulice', models.CharField(max_length=255, verbose_name='Ulice')),
                ('mesto', models.CharField(max_length=255, verbose_name='Město')),
                ('psc', models.CharField(max_length=20, verbose_name='PSČ')),
            ],
            options={
                'verbose_name': 'Pojištěnec',
                'verbose_name_plural': 'Pojištěnci',
            },
        ),
        migrations.AlterField(
            model_name='uzivatel',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
