# Generated by Django 4.1 on 2022-09-22 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0005_pojistenec_alter_uzivatel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typ_pojisteni',
            fields=[
                ('typ', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Typ')),
            ],
            options={
                'verbose_name': 'Typ pojištění',
                'verbose_name_plural': 'Typy pojištění',
            },
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='telefon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='ulice',
            field=models.CharField(max_length=255, verbose_name='Ulice a číslo popisné'),
        ),
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castka', models.PositiveBigIntegerField(verbose_name='Částka')),
                ('predmet_pojisteni', models.CharField(max_length=255, verbose_name='Předmět pojištění')),
                ('platnost_od', models.DateField(verbose_name='Platnot od')),
                ('platnost_do', models.DateField(verbose_name='Platnot do')),
                ('id_pojistenec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence_pojisteni.pojistenec', verbose_name='Typ')),
                ('typ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence_pojisteni.typ_pojisteni', verbose_name='Typ')),
            ],
            options={
                'verbose_name': 'Pojištění',
                'verbose_name_plural': 'Pojištění',
            },
        ),
    ]
