# Generated by Django 4.1 on 2022-09-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0007_remove_pojisteni_id_pojistenec_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pojisteni',
            old_name='predmet_pojisteni',
            new_name='predmet',
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='castka',
            field=models.PositiveBigIntegerField(verbose_name='Částka (Kč)'),
        ),
        migrations.CreateModel(
            name='Udalost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castka', models.PositiveBigIntegerField(verbose_name='Částka (Kč)')),
                ('predmet', models.CharField(max_length=255, verbose_name='Předmět pojištění')),
                ('datum', models.DateField(verbose_name='Platnot od')),
                ('popis', models.TextField(verbose_name='Popis události')),
                ('id_pojistence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence_pojisteni.pojistenec', verbose_name='id pojištěnce')),
                ('id_pojisteni', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence_pojisteni.pojisteni', verbose_name='id pojištění')),
            ],
            options={
                'verbose_name': 'Událost',
                'verbose_name_plural': 'Události',
            },
        ),
    ]
