# Generated by Django 4.1 on 2022-10-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0009_remove_udalost_id_pojistence_alter_udalost_datum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzivatel',
            old_name='is_admin',
            new_name='je_admin',
        ),
    ]
