# Generated by Django 4.1 on 2022-10-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0010_rename_is_admin_uzivatel_je_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzivatel',
            old_name='je_admin',
            new_name='is_admin',
        ),
    ]
