# Generated by Django 4.1 on 2022-10-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0011_rename_je_admin_uzivatel_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzivatel',
            old_name='is_admin',
            new_name='je_admin',
        ),
    ]
