# Generated by Django 4.1 on 2022-10-04 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0013_rename_je_admin_uzivatel_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzivatel',
            name='id_pojistence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evidence_pojisteni.pojistenec', verbose_name='id pojištěnce'),
        ),
    ]
