# Generated by Django 4.1 on 2022-10-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0014_uzivatel_id_pojistence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzivatel',
            name='id_pojistence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evidence_pojisteni.pojistenec', verbose_name='id pojištěnce'),
        ),
    ]
