# Generated by Django 4.1 on 2022-10-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0015_alter_uzivatel_id_pojistence'),
    ]

    operations = [
        migrations.AddField(
            model_name='udalost',
            name='id_pojistence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence_pojisteni.pojistenec', verbose_name='id pojištěnce'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
    ]
