# Generated by Django 4.1 on 2022-10-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0016_udalost_id_pojistence_alter_pojistenec_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojisteni',
            name='id_pojistence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence_pojisteni.pojistenec', verbose_name='id pojištěnce'),
        ),
        migrations.AlterField(
            model_name='udalost',
            name='id_pojistence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence_pojisteni.pojistenec', verbose_name='id pojištěnce'),
        ),
        migrations.AlterField(
            model_name='udalost',
            name='id_pojisteni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence_pojisteni.pojisteni', verbose_name='id pojištění'),
        ),
    ]
