# Generated by Django 4.1 on 2022-10-10 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0017_alter_pojisteni_id_pojistence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojisteni',
            name='typ',
            field=models.ForeignKey(default='Nezařazeno', on_delete=django.db.models.deletion.SET_DEFAULT, to='evidence_pojisteni.typ_pojisteni', verbose_name='Typ pojištění'),
        ),
    ]
