# Generated by Django 4.1 on 2022-10-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0018_alter_pojisteni_typ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pojisteni',
            old_name='id_pojistence',
            new_name='pojistenec',
        ),
        migrations.RenameField(
            model_name='udalost',
            old_name='id_pojistence',
            new_name='pojistenec',
        ),
        migrations.RenameField(
            model_name='udalost',
            old_name='id_pojisteni',
            new_name='pojisteni',
        ),
        migrations.RenameField(
            model_name='uzivatel',
            old_name='id_pojistence',
            new_name='pojistenec',
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
