# Generated by Django 4.1 on 2022-10-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0019_rename_id_pojistence_pojisteni_pojistenec_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzivatel',
            options={'verbose_name': 'Uživatel', 'verbose_name_plural': 'Uživatelé'},
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='pojistenec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence_pojisteni.pojistenec', verbose_name='Pojištěnec'),
        ),
        migrations.AlterField(
            model_name='udalost',
            name='pojistenec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence_pojisteni.pojistenec', verbose_name='Pojištěnec'),
        ),
        migrations.AlterField(
            model_name='udalost',
            name='pojisteni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence_pojisteni.pojisteni', verbose_name='Pojištění'),
        ),
        migrations.AlterField(
            model_name='uzivatel',
            name='pojistenec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evidence_pojisteni.pojistenec', verbose_name='Pojištěnec'),
        ),
    ]
