# Generated by Django 4.1 on 2022-10-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0020_alter_uzivatel_options_alter_pojisteni_pojistenec_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzivatel',
            old_name='is_admin',
            new_name='je_admin',
        ),
    ]
