# Generated by Django 4.1 on 2022-11-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0021_rename_is_admin_uzivatel_je_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojistenec',
            name='fotografie',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
