# Generated by Django 4.1.3 on 2022-11-30 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0022_pojistenec_fotografie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clanek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255, verbose_name='Název')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True, verbose_name='Datum a čas vytvoření')),
                ('obsah', models.TextField(verbose_name='Obsah')),
                ('vlastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Článek',
                'verbose_name_plural': 'Články',
                'ordering': ['vytvoreno'],
            },
        ),
    ]
