# Generated by Django 4.1.3 on 2022-11-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0023_clanek'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanek',
            name='aktualizovano',
            field=models.DateTimeField(auto_now=True, verbose_name='Naposledy změněno'),
        ),
        migrations.AlterField(
            model_name='clanek',
            name='vytvoreno',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno'),
        ),
    ]
