# Generated by Django 4.1.3 on 2022-12-01 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0024_clanek_aktualizovano_alter_clanek_vytvoreno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanek',
            name='vlastnik',
        ),
        migrations.AddField(
            model_name='clanek',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clanky', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
